### PR TITLE
Added skipImmediate Option in repeatEvery Method

### PR DESCRIPTION
**Pull request by arihantdaga**
Referring to issues https://github.com/agenda/agenda/issues/457 and https://github.com/agenda/agenda/issues/422

### CODE REVIEW

**Comment by arihantdaga** [comment]
@simison Can u review..?

**Comment by himanshuphirke** [comment]
@simison Could you approve this? The absence of this creates lot of issues in repeating jobs.

For example, if a job has to send email lets say every day, every server restart will send an email.

**Comment by himanshuphirke** [comment]
@simison - What is the frequency when www.npmjs.com gets updated library?
Is there any defined timeline or specific date when its released there?

**Comment by simison** [comment]
Agenda v2.0.0 was just published together with `skipImmediate` option.

Sorry it took a while, but this release had a ton going on (it's a big rewrite). Enjoy!

**Pull request merged**
