### PR TITLE
Added Agendash2

### PR DESCRIPTION
**Pull request by ronenteva**

### CODE REVIEW

**Comment by simllll** [comment]
Love this tool, some unfortunately some bugs (e.g. last updated & locked at is wrong), and also ther eis no "select all" thingy ;)

**Comment by simison** [comment]
Copying from Slack https://agendajs.slack.com/archives/C6SUP3ZUJ/p1595854627004700

> Your work seems great! What do you think about bringing it to Agenda Github org and use it from there? Is it at feature parity with agendash and could it just replace it? (and happy for you to have access at Agenda  of course)

**Comment by ronenteva** [comment]
Not my work, I just added it to the list because I thought Agenda users should know it exists.
@santiq

**Review by santiq — DISMISSED** [review]

**Comment by leonardlin** [comment]
retry after marging back with updates of: https://github.com/agenda/agenda/pull/1086

**Review by leonardlin — APPROVED** [review]

**Pull request merged**
