### PR TITLE
added drain func

### PR DESCRIPTION
**Pull request by nmehmedrnd**
Basically adds function which waits till all currently running jobs finishes, for more graceful stop

### CODE REVIEW

**Comment by harisvsulaiman** [comment]
@nmehmedrnd Would you mind adding some tests?

**Comment by nedyalkov** [comment]
Looks good to me, but it is indeed missing tests.

**Review by harisvsulaiman — APPROVED** [review]

**Comment by harisvsulaiman** [comment]
@nmehmedrnd Thank you for your contribution. 🚀🚀🚀

**Comment by koresar** [comment]
Published as v4.4.0. See History.md: https://github.com/agenda/agenda/blob/master/History.md

**Pull request merged**
