### PR TITLE
Update documentation to reflect Mongo v3

### PR DESCRIPTION
**Pull request by simison**
https://github.com/agenda/agenda/blob/master/lib/agenda/db-init.js#L40-L42

https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/#db.collection.createIndex

I'm not sure if this should be done only on agenda ready event or directly at the custom collection before its passed to Agenda?

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
I think we should be fine with on ready. If we get any users reporting issues we'll have a look more into this. Since this should trigger the background index building we should have no difference when we run it.

**Comment by simison** [comment]
Aight, feel free to merge / approve-review!

**Comment by simison** [comment]
BTW Creating index could be a public `agenda.createIndex()` method?

**Comment by OmgImAlexis** [comment]
Sounds good to me.

**Pull request merged**
