### PR TITLE
Fixed deprecation warning for collection.findOneAndUpdate

### PR DESCRIPTION
**Pull request by frobinsonj**
Resolves issue #1327 

Had to update @types/mongodb so pull request #1318 can be closed.

@koresar could you please review.

Thanks.

### CODE REVIEW

**Review by koresar — APPROVED** [review]

**Comment by koresar** [comment]
Thanks for the PR! It looks like the thing we need. :)

Not sure when this will be released. I think this can wait, it's just a warning.
Let's wait for more changes before publishing your fix to NPM.

**Comment by mashpie** [comment]
Great to see that this was fixed and merged. Do you have any eta on when the fix will be released?

**Comment by koresar** [comment]
Hello all.
Sad news. This PR broke unit tests. Namely the `unique()` feature.
I had to revert this PR in #1362 

Fun fact. When this PR was merged it did pass the unit tests in CI. However, then the bloody Dependabot came in and updated the `mongodb` driver npm package changes from this PR become breaking.

I have no idea what to do.

**Comment by koresar** [comment]
I know what to do. Fix the issue using the proposed way: https://github.com/agenda/agenda/issues/1327#issuecomment-857290182

**Pull request merged**
