### PR TITLE
update database.js to remove the deprecation warning for useNewUrlParser

### PR DESCRIPTION
**Pull request by dpawson905**
add useNewUrlParser: true to database.js

### CODE REVIEW

**Comment by dpawson905** [comment]
Any idea when this will be merged?

**Comment by shellscape** [comment]
@dandv @simison folks, can we get a peek at this please?

**Comment by firecrackerz** [comment]
@dpawson905 any update on this?

**Comment by dpawson905** [comment]
> @dpawson905 any update on this?

No, I haven't heard anything

**Comment by dpawson905** [comment]
No, I haven't heard anything

**Comment by lqmanh** [comment]
Hi,
Are there any chances of this fix being merged?
There are some other PRs like #737 and #744 trying to solve the same problem, and this one was even approved by one of the admins.

**Pull request merged**
