### PR TITLE
swap eslint for xo

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This is cause all PRs to be invalid as this changes almost every line in every file.

@lushc should we hold off on this until most of the high priority PRs are merged or should we just rebase them all? This took me less than 30 minutes so I don't mind closing this and redoing it later on. Just wanted to show the changes so everyone can see how xo works over eslint.

Closes https://github.com/agenda/agenda/issues/455

### CODE REVIEW

**Comment by simison** [comment]
>should we hold off on this until most of the high priority PRs are merged or should we just rebase them all

I'd say wait at least until the ones which have higher changes getting in within ~2 weeks?

eslint is working now in master already so that improves things greatly.

**Comment by OmgImAlexis** [comment]
Alright, I'll close this off and delete the branch since rebasing this on top of other PRs is going to be a nightmare. @lushc can you let me know once you've merged some of the higher priority PRs and then I'll add this all back in.

**Comment by simison** [comment]
@OmgImAlexis I'd say let's try to squeeze these in within next 2-3 weeks: https://github.com/agenda/agenda/milestone/1 ? 

If it happens so that those get in faster — awesome — if not until ~2 weeks, then leave those left to next version and go ahead with XO+publish 0.10.0.

WDYT?

**Comment by OmgImAlexis** [comment]
Sounds good to me. Any idea who has permission to publish to npm? We're going to need them once we finish all the PRs from that milestone.

**Comment by lushc** [comment]
Looks great, I agree with @simison and say we give it a couple of weeks, I think it'll be better to "break" the older PRs in favour of making it easier to accept new contributions.

**Comment by simison** [comment]
I believe @joeframbach has npm rights? 

@lushc and @OmgImAlexis should totally have them as well I think.

**Comment by OmgImAlexis** [comment]
I don't want them, I tend to fuck up releases so I leave that to others. 😮

**Comment by joeframbach** [comment]
I have npm rights to agendash, not agenda.

**Comment by simison** [comment]
@OmgImAlexis _Never be afraid to break things._ ;-) Maybe if there's a clear procedure to follow and written down on wiki?

**Comment by OmgImAlexis** [comment]
@simison last time I handled a release I accidentally force pushed a new git repo over my last 2 years of works so.... *hides*

**Comment by OmgImAlexis** [comment]
Adding something to the wiki or a npm script would be the best bet.

**Comment by simison** [comment]
Well, good thing about breaking stuff is that now you won't make that same mistake never again. :-)

**Pull request closed without merging**
