### PR TITLE
Update README badges

### PR DESCRIPTION
**Pull request by OmgImAlexis**
@agenda/maintainers someone will need to enable David-dm, Code Climate and Coveralls for this to be merged.

### CODE REVIEW

**Comment by simison** [comment]
@joeframbach you've got access to those?

(Ping @rschmukler you might need to help out here)

**Comment by joeframbach** [comment]
I've approved CodeClimate and Coveralls.

**Comment by joeframbach** [comment]
I've granted access to david-dm. I think this PR is all set.

**Comment by OmgImAlexis** [comment]
LGTM.

**Pull request merged**
