### PR TITLE
Feature/update deps

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Replaces https://github.com/agenda/agenda/pull/637

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
If someone could fix these two issues that'd be great.

```
➜  agenda git:(feature/update-deps) ✗ xo

  lib/agenda/save-job.js:8:4
  ⚠  8:4  Expected JSDoc for job but found err.  valid-jsdoc

  lib/agenda/start.js:5:1
  ⚠  5:1  Missing JSDoc return description.      valid-jsdoc

  2 warnings
```

**Comment by OmgImAlexis** [comment]
Please don't merge this just yet as I'm going to add some other updates here too.

**Comment by simison** [comment]
LGTM already now!

I'd say because this touches so many files, merge this already now and spin up another PR for the other updates in case it gets blocked by something (even by just lack of time to work on it).

**Comment by simison** [comment]
Recorded those warnings as a todo here: https://github.com/agenda/agenda/issues/658

**Pull request merged**
