### PR TITLE
Merge: bring agendaTS into agenda main repo

### PR DESCRIPTION
**Pull request by harisvsulaiman**
Refer  #1502

### CODE REVIEW

**Review by koresar — APPROVED** [review]
Sorry for the delay. I fully trust your reviews. Tell me what to do?

**Comment by harisvsulaiman** [comment]
@koresar I guess this pr satisfied @simllll first requirement as to retain history of agendats while merging. 

I guess this will be the first step.

**Comment by simllll** [comment]
Hi guys, sorry for the delay/silence from my side, I still have [this](https://github.com/agenda/agenda/issues/1502) on my agenda, I hope I can bring this forward during the next few weeks :)

**Comment by harisvsulaiman** [comment]
> Hi guys, sorry for the delay/silence from my side, I still have [this](https://github.com/agenda/agenda/issues/1502) on my agenda, I hope I can bring this forward during the next few weeks :)

Should I merge this or should I wait for @simllll to review it?

**Comment by simllll** [comment]
As I'm unsure in which state the project is after the merge, i would prefer to wait before merging. But on the other hand i really don't wanna black any progress here, so if you find some time it's more than welcome from my side to bring this into the master and draft some next major alpha release?

**Comment by harisvsulaiman** [comment]
@simllll this pr simply addresses these tasks in the issue #1503 
```
1.  try to create a PR that is based on the current agenda master, and try to keep as many commits from the agendaTS to have a change history. in case of merge conflicts, keep the agendaTS code.
2. rename everything back to agenda
```

**Pull request merged**
