### PR TITLE
Added method to close database connection

### PR DESCRIPTION
**Pull request by luismesas**
This allows cucumber tests to close gracefully after each scenario using agenda.

### CODE REVIEW

**Comment by rschmukler** [comment]
@luismesas sorry on the delay. Can you please add tests / docs for this?

**Comment by luismesas** [comment]
will do. sortly

**Comment by mdlavin** [comment]
Any update on this?  I ran into the same problem recently and I was about to put a pull request up when I noticed this.  If there is anything I can do to help, let me know.

**Comment by luismesas** [comment]
Hi, the fix solves the issue, but I didn't found the time to do the tests...

**Comment by rschmukler** [comment]
@mdlavin if you can submit tests that'd be a huge help!

**Comment by richsilv** [comment]
If anybody else has this issue, note that you can just `agenda._mdb.close(force, cb)` to close the db connection.

**Comment by simison** [comment]
@luismesas if you wanna have a look and review my similar PR with tests, would be awesome!

https://github.com/agenda/agenda/pull/450

I'll close this one.

**Pull request closed without merging**
