### PR TITLE
cleanup tests

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This switches the test requires to using const instead of var and splits the file into three separate files so they're easier to manage.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@simison looks good?

**Comment by simison** [comment]
Skimmed through quickly and looks good! I like splitting them into multiple
files.

On 26 Jul 2017 11:49, "Alexis Tyler" <notifications@github.com> wrote:

@simison <https://github.com/simison> looks good?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/agenda/agenda/pull/487#issuecomment-317990675>, or mute
the thread

**Comment by OmgImAlexis** [comment]
Shall I merge or wait for a LGTM from another member?

**Comment by lushc** [comment]
Might as well go all the way and replace the remaining instances of `var` with `let`?

**Comment by OmgImAlexis** [comment]
I was going to do that once this is merged along with more xo changes.

**Comment by lushc** [comment]
Alright cool, LGTM!

**Pull request merged**
