### PR TITLE
Add Node.js 7 and 8 to Travis CI

### PR DESCRIPTION
**Pull request by simison**
Tests with Node.js 7 and 8

Travis Docs:
- [Fast Finishing](https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing)
- [Rows that are Allowed to Fail](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail)

### CODE REVIEW

**Comment by simison** [comment]
@rschmukler @joeframbach could you enable Travis from your profile on Travis-ci.org: https://travis-ci.org/profile/

**Comment by joeframbach** [comment]
Done! I've fixed the readme badges for Travis, but the david-dm, codeclimate, and coveralls badges I left alone.

**Comment by simison** [comment]
_(Closing+ re-opening to run Travis.)_

**Comment by simison** [comment]
Removed Node.js 7 and 8 from "allowed failures" since they seemed to pass just fine => _squashing and merging_ on my own since it's just Travis.

**Pull request merged**
