### PR TITLE
Example illustrating concurrency and locking

### PR DESCRIPTION
**Pull request by dandv**
To help #781.

### CODE REVIEW

**Comment by wingsbob** [comment]
Might be a bit clearer what the lock is about if you created more than 1 instance of `agenda`, and explained that only 1 instance would be able to work on the job?

Also, this doesn't look to have any example(s) for the concurrency setting(s)

**Comment by dandv** [comment]
Happy to add those next, or in a separate example. This is the first example in the repo after all, and I'd like it to help folks like @mohitzim (see #781) understand how one instance Agenda works.

**Comment by wingsbob** [comment]
Ok. I feel there's 2 different opinions on how locking should work.

The default behaviour of agenda is to lock jobs for much longer than it should take for them to process, and assume that if that expires, then agenda crashed while processing/with the job queued.

Your example kinda leans more towards having a very short lock time, and refreshing that lock in the job processor. This might cause some slightly odd behaviour, as agenda would still have the job in it's locked queue if the concurrency limit has been reached, and could result in a lot of unnecessary mongo queries. (getting slightly off-topic there)

I think an example of a job which never calls `done` for the first 2 tries shows the default behaviour of the lock more clearly, but there seems to be some strong opinions on which approach to take.

¯\\\_(ツ)_/¯

**Comment by gianpaj** [comment]
Could this be merged? It took me a long time to find this PR, which code is pretty helpful.

Thanks

**Comment by zentrapool** [comment]
I've had problem dealing abnormal behaviors with long running jobs. 
This code is very useful. hope this PR can be merge to help many Agenda users.

**Comment by OmgImAlexis** [comment]
Is this able to be updated or should it be closed?

**Comment by simison** [comment]
cc @koresar @leonardlin thoughts on this one or shall we close?

**Comment by koresar** [comment]
I don't have an opinion. But few people said that it's a useful thing.
I'd rather have an example like that.

Can't be merged yet because CI...

**Comment by santiq** [comment]
IMO this example is pretty useful, since it ilustrates how to use `job.touch()` with `lockLifetime`

**Comment by leonardlin** [comment]
oh, it fails because of linting errors, hmm, we need to make a big linting fix PR

Otherwise I have nothing against the example.

**Comment by simison** [comment]
Rebased and sorted lint errors.

**Review by simison — APPROVED** [review]

**Pull request merged**
