### PR TITLE
xo linting

### PR DESCRIPTION
**Pull request by leonardlin**
`yarn lint` works again.
It was missing the typescript config.

xo is supposed to come with default linting rules. Since there is existing code with history, I added some adjustment to the rules, to minimize the "adjustment work".

Please have a look what you think of it.

This PR only makes linting work again.
Future separate PR: adjust files to adhere to the linting rules

### CODE REVIEW

**Comment by simllll** [comment]
Nice work (y) from my side LGTM, but let's wait for @OmgImAlexis and @simison

**Review by simison — APPROVED** [review]
Thank you!

**Comment by simison** [comment]
@leonardlin Feel free to merge this after rebase. :-)

**Comment by simison** [comment]
I think we can add `yarn lint` into Travis config already in this PR. What do you think? Happy to have it as a follow-up as well.

**Comment by leonardlin** [comment]
> I think we can add `yarn lint` into Travis config already in this PR. What do you think? Happy to have it as a follow-up as well.

Unfortunately not yet.
It will fail horribly. Still a lot of cleanup necessary.

**Comment by leonardlin** [comment]
> 
> 
> Thank you! Feel free to merge.

@simison Thanks. I have updated the branch with the latest from master that it's not failing on test anymore.
Unfortunately I can't approve my own PR

**Review by simison — APPROVED** [review]
Here ya go. :-)

**Pull request merged**
