### PR TITLE
fix whitespace and indentation

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This cleans up unneeded whitespace and fixes some indentation so it's a little easier to read.

### CODE REVIEW

**Comment by simison** [comment]
Weird:

image

```
  agenda
    Agenda
      1) "before each" hook
      2) "after each" hook
  agenda
    Job
      repeatAt
        3) "before each" hook
        4) "after each" hook
  agenda
    Retry
      5) "before each" hook
      6) "after each" hook
  0 passing (413ms)
  6 failing
  1) agenda "before each" hook:
     Uncaught TypeError: Cannot read property 'collection' of null
      at clearJobs (test/agenda.js:19:8)
      at Timeout._onTimeout (test/agenda.js:43:11)
  2) agenda "after each" hook:
     Uncaught TypeError: Cannot read property 'updateMany' of undefined
      at module.exports.Agenda._unlockJobs (lib/agenda.js:755:19)
      at module.exports.Agenda.stop (lib/agenda.js:659:8)
      at Timeout._onTimeout (test/agenda.js:57:12)
  3) agenda "before each" hook:
     Uncaught TypeError: Cannot read property 'collection' of null
      at clearJobs (test/job.js:19:8)
      at Timeout._onTimeout (test/job.js:43:11)
  4) agenda "after each" hook:
     Uncaught TypeError: Cannot read property 'updateMany' of undefined
      at module.exports.Agenda._unlockJobs (lib/agenda.js:755:19)
      at module.exports.Agenda.stop (lib/agenda.js:659:8)
      at Timeout._onTimeout (test/job.js:57:12)
  5) agenda "before each" hook:
     Uncaught TypeError: Cannot read property 'collection' of null
      at clearJobs (test/retry.js:19:8)
      at Timeout._onTimeout (test/retry.js:43:11)
  6) agenda "after each" hook:
     Uncaught TypeError: Cannot read property 'updateMany' of undefined
      at module.exports.Agenda._unlockJobs (lib/agenda.js:755:19)
      at module.exports.Agenda.stop (lib/agenda.js:659:8)
      at Timeout._onTimeout (test/retry.js:57:12)
make: *** [test-once] Error 6
The command "make test-once" exited with 2.
```

...I'll re-run Travis by closing+opening.

**Comment by simison** [comment]
LGTM

**Comment by OmgImAlexis** [comment]
@simison I noticed that there are some documents left in mongodb and by clearing it before running the tests locally I didn't get any issues at all. If I left the docs then randomly I'd get issues with the tests failing. I wonder if that's the cause?

**Comment by simison** [comment]
@OmgImAlexis could be, I've had the same happening with few other projects before.

Mongo [`db.dropDatabase`](https://docs.mongodb.com/manual/reference/method/db.dropDatabase/) is handy to do at the very beginning of tests (or even in between).

**Comment by OmgImAlexis** [comment]
@simison @lushc maybe we should try adding that before all the test files run and see if it fixes it?

**Comment by simison** [comment]
There _might_ be more to it as it happens so randomly, but that would at least help tests pass when they should.

**Comment by emhagman** [comment]
Since we have started to fix whitespace and indentation, do you think it is time to start using `xo` in the code?

**Comment by OmgImAlexis** [comment]
@simison sounds good to me.

@emhagman I want to fix up some more of the styling before adding xo otherwise we'll end up with a massive PR/commit again. It'll be easier to slowly lint the files and merge them in parts so everyone can rebase the current PRs.

I would like to get `xo` added before 1.0.0 is published.

**Pull request merged**
