### PR TITLE
Fix schedule for getting a single name

### PR DESCRIPTION
**Pull request by thebestnom**
Sorry if it looks bad, I did it quickly from my phone as an example

### CODE REVIEW

**Comment by koresar** [comment]
I'm not an expert. But to me, deflating a type to use some sounds like we better be without the type.

I suggest removing both new types. And using string|string[] and Job|Job[]

Also, I'm not a TS expert. So let's just for other onions.

**Comment by leonardlin** [comment]
I agree with the problem, that we have a lot of function definition that take multiple types as argument.

I don't know if it's got practice to create a type as a workaround.

I think it would be better to cleanup the code, but I defer here to others as well.
Whenever I worked on the types, the cleanup was often non-trivial, that I just went with the bad types.

**Comment by thebestnom** [comment]
I dont think it's a workaround, we can easily infer return type based on sent type, it not that uncommon to do (users dont have to insert the generic, it's automatically infered based on argument)

**Comment by thebestnom** [comment]
Other way is to do function overloading like https://stackoverflow.com/questions/57244402/typescript-infer-return-type-from-used-arguments

**Comment by simllll** [comment]
Would recommend function overloading, but for getting this to work I guess it is mandatory to have classes. And right now the code isn't structured like this (more the opposite with all the overloading from different files), but I also would vote for it to get it into a nicely dressed class style ;-) see @hokify/agenda as example

**Comment by thebestnom** [comment]
I don't think function overloading require class, let me test that

**Comment by simllll** [comment]
> I don't think function overloading require class, let me test that

It's possible to just define multiple defintions for overloading, but not with prototype overwrites like it is now. At least as far as I know. Besides that there are some other issues with exporting the type in case it's not bound to a class, but that shouldn't be a deal breaker.

e.g. 
this works:
```
function add(a: number, b: number, c: number): number;
function add(a: number, b: number): any;
function add(a: string, b: string): any;

function add(a: any, b: any, c?: any): any {
```

but exporting will not, or at least I'm not aware of any syntax that would be "usable" enough (you always can overload it manually  via defintion file of course;)).
```
export const database = function (this: Agenda)
export const database = function (
  this: Agenda,
  url?: string
  );
export const database = function (
  this: Agenda,
  url?: number
  );
export const database = function (
  this: Agenda,
  url?: any
  ) { .. }
```

**Comment by thebestnom** [comment]
testing this now

**Comment by thebestnom** [comment]
Ok, pushed with operator overloading, looks like it's working (tested by creating new Agenda and calling schedule

**Comment by thebestnom** [comment]
there is a second way of doing this with const but that requires return type any (no return check) with https://stackoverflow.com/a/53143568

**Review by koresar — APPROVED** [review]

**Comment by koresar** [comment]
Beautiful!
@simllll should we merge?

**Review by simllll — APPROVED** [review]

**Pull request merged**
